services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - infra_net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: my-topic:1:1,another-topic:2:1
    networks:
      - infra_net

  kafka-topics:
    build:
      context: ./  # путь к папке с Dockerfile
    container_name: kafka-topics
    networks:
      - infra_net
    depends_on:
      - kafka
      - zookeeper

networks:
  infra_net:
    external: true