services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - infra_net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: -Xmx256M -Xms128M
    networks:
      - infra_net
  db:
    image: postgres:12
    container_name: db
#    ports:
#      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - infra_net
  kafka-topics:
    build:
      context: ./  # путь к папке с Dockerfile
    container_name: kafka-topics
    networks:
      - infra_net
    depends_on:
      - kafka
      - zookeeper
      - db
networks:
  infra_net:
    external: true

volumes:
  db-data: